name: Run FastAPI

on: [push]

jobs:
  run-fastapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run FastAPI
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000
